import { botCache, Collection, Image } from "../../../../deps.ts";

botCache.constants.themes = new Collection([
  ["white", {
    id: "white",
    rectangle: await Image.decode(
      Deno.readFileSync(
        new URL(
          "./../../../../assets/profile/left_rectangle_white.png",
          import.meta.url,
        ),
      ),
    ),
    username: `#000`,
    discriminator: `#adadad`,
    userdivider: `#dadada`,
    xpbarText: `#000`,
    xpbarRatioUp: `#000`,
    xpbarRatioDown: `#000`,
    badgeShadow: `rgba(161,161,161,1)`,
    badgeFilling: `#e0e0e0`,
    xpbarFilling: `#e0e0e0`,
    clanRectFilling: `rgba(54,54,54,.7)`,
    clanName: `#8bccef`,
    clanText: `#fff`,
    clanURL: `#fff`,
  }],
  ["black", {
    id: "black",
    rectangle: await Image.decode(
      Deno.readFileSync(
        new URL(
          "./../../../../assets/profile/left_rectangle_black.png",
          import.meta.url,
        ),
      ),
    ),
    username: `#fff`,
    discriminator: `#fff`,
    userdivider: `#dadada`,
    xpbarText: `#fff`,
    xpbarRatioUp: `#000`,
    xpbarRatioDown: `#000`,
    badgeShadow: `rgba(100,100,100,.7)`,
    badgeFilling: `#5D5D5D`,
    xpbarFilling: `#5D5D5D`,
    clanRectFilling: `rgba(54,54,54,.7)`,
    clanName: `#8bccef`,
    clanText: `#fff`,
    clanURL: `#fff`,
  }],
  ["orange", {
    id: "orange",
    rectangle: await Image.decode(
      Deno.readFileSync(
        new URL(
          "./../../../../assets/profile/left_rectangle_orange.png",
          import.meta.url,
        ),
      ),
    ),
    username: `#000`,
    discriminator: `#000`,
    userdivider: `#dadada`,
    xpbarText: `#000`,
    xpbarRatioUp: `#000`,
    xpbarRatioDown: `#000`,
    badgeShadow: `rgba(100,100,100,.7)`,
    badgeFilling: `#5d5d5d`,
    xpbarFilling: `#5d5d5d`,
    clanRectFilling: `rgba(54,54,54,.7)`,
    clanName: `#8bccef`,
    clanText: `#fff`,
    clanURL: `#fff`,
  }],
  ["red", {
    id: "red",
    rectangle: await Image.decode(
      Deno.readFileSync(
        new URL(
          "./../../../../assets/profile/left_rectangle_red.png",
          import.meta.url,
        ),
      ),
    ),
    username: `#fff`,
    discriminator: `#fff`,
    userdivider: `#dadada`,
    xpbarText: `#fff`,
    xpbarRatioUp: `#000`,
    xpbarRatioDown: `#000`,
    badgeShadow: `rgba(100,100,100,.7)`,
    badgeFilling: `#5d5d5d`,
    xpbarFilling: `#5d5d5d`,
    clanRectFilling: `rgba(54,54,54,.7)`,
    clanName: `#8bccef`,
    clanText: `#fff`,
    clanURL: `#fff`,
  }],
  ["green", {
    id: "green",
    rectangle: await Image.decode(
      Deno.readFileSync(
        new URL(
          "./../../../../assets/profile/left_rectangle_green.png",
          import.meta.url,
        ),
      ),
    ),
    username: `#fff`,
    discriminator: `#fff`,
    userdivider: `#dadada`,
    xpbarText: `#fff`,
    xpbarRatioUp: `#000`,
    xpbarRatioDown: `#000`,
    badgeShadow: `rgba(100,100,100,.7)`,
    badgeFilling: `#5D5D5D`,
    xpbarFilling: `#5D5D5D`,
    clanRectFilling: `rgba(54,54,54,.7)`,
    clanName: `#8bccef`,
    clanText: `#fff`,
    clanURL: `#fff`,
  }],
  ["purple", {
    id: "purple",
    rectangle: await Image.decode(
      Deno.readFileSync(
        new URL(
          "./../../../../assets/profile/left_rectangle_purple.png",
          import.meta.url,
        ),
      ),
    ),
    username: `#fff`,
    discriminator: `#fff`,
    userdivider: `#dadada`,
    xpbarText: `#fff`,
    xpbarRatioUp: `#000`,
    xpbarRatioDown: `#000`,
    badgeShadow: `rgba(100,100,100,.7)`,
    badgeFilling: `#5D5D5D`,
    xpbarFilling: `#5D5D5D`,
    clanRectFilling: `rgba(54,54,54,.7)`,
    clanName: `#8bccef`,
    clanText: `#fff`,
    clanURL: `#fff`,
  }],
  ["blue", {
    id: "blue",
    rectangle: await Image.decode(
      Deno.readFileSync(
        new URL(
          "./../../../../assets/profile/left_rectangle_blue.png",
          import.meta.url,
        ),
      ),
    ),
    username: `#fff`,
    discriminator: `#fff`,
    userdivider: `#dadada`,
    xpbarText: `#fff`,
    xpbarRatioUp: `#000`,
    xpbarRatioDown: `#000`,
    badgeShadow: `rgba(100,100,100,.7)`,
    badgeFilling: `#5D5D5D`,
    xpbarFilling: `#5D5D5D`,
    clanRectFilling: `rgba(54,54,54,.7)`,
    clanName: `#8bccef`,
    clanText: `#fff`,
    clanURL: `#fff`,
  }],
]);
